config/routes.rb
Nyanda::Application.routes.draw do
  get "search/result"
	devise_for :users, :controllers => {:registrations => "users/registrations"}, skip: [:sessions, :registrations]
	devise_scope :user do
		get '/in', to: 'devise/sessions#new', as: :new_user_session
		post '/in', to: 'devise/sessions#create', as: :user_session
		get '/out', to: 'devise/sessions#destroy', as: :destroy_user_session

		# users/registrations paths
		post '/joinus', to: 'users/registrations#create', as: :user_registration
		get '/joinus', to: 'users/registrations#new', as: :new_user_registration
		get '/me', to: 'users/registrations#edit', as: :edit_user_registration
		patch '/me', to: 'users/registrations#update', as: nil
		put '/me', to: 'users/registrations#update', as: nil
		delete '/me', to: 'users/registrations#destroy', as: nil
	end
#	devise_for :admin_users, ActiveAdmin::Devise.config
#	ActiveAdmin.routes(self)
	resources :search, :only => [:result, :get_result] do
    collection do
      match 'result' => 'search#result', via: [:get, :post], as: :result
    end
	end
	resources :comments, :only => [:create]
	resources :categories, :only => [:create, :destroy], :path => '/c' do
		resources :boards, :only => [:index], :path => '' do
	    resources :topics, :path => '' do
	    	get 'page/:page', :action => :index, :on => :collection
	    end
	  end
	end
	get 'vote', to: 'votings#vote_to_topic'
	get 'tags/:tag', to: 'tags#index', as: :tag
	get "home/index"
	get 'about', to: 'home#about', as: :about
	get 'sextant_mount', to: "sextant/routes#index"
	root :to => "home#index"

	get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
	# Example of regular route:
	#   get 'products/:id' => 'catalog#view'

	# Example of named route that can be invoked with purchase_url(id: product.id)
	#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

	# Example resource route (maps HTTP verbs to controller actions automatically):
	#   resources :products

	# Example resource route with options:
	#   resources :products do
	#     member do
	#       get 'short'
	#       post 'toggle'
	#     end
	#
	#     collection do
	#       get 'sold'
	#     end
	#   end

	# Example resource route with sub-resources:
	#   resources :products do
	#     resources :comments, :sales
	#     resource :seller
	#   end

	# Example resource route with more complex sub-resources:
	#   resources :products do
	#     resources :comments
	#     resources :sales do
	#       get 'recent', on: :collection
	#     end
	#   end

	# Example resource route with concerns:
	#   concern :toggleable do
	#     post 'toggle'
	#   end
	#   resources :posts, concerns: :toggleable
	#   resources :photos, concerns: :toggleable

	# Example resource route within a namespace:
	#   namespace :admin do
	#     # Directs /admin/products/* to Admin::ProductsController
	#     # (app/controllers/admin/products_controller.rb)
	#     resources :products
	#   end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_attached_file :clip, 
										:styles => {
											:medium => "300x300>",
											:thumb => "100x100>",
											:mini_thumb => "100x100"
											},
										:convert_options => {
   										:mini_thumb  => "-gravity Center -crop 50x50+0+0"
 										}

	# relationship
	has_many :comments, :dependent => :destroy
	has_many :votings, :dependent => :destroy
	has_many :topic_visits, :dependent => :destroy
	belongs_to :user
	belongs_to :board

	# validattion
	validates :title, :content, presence: true
	validates :category_id, :board_id, presence: true

	# image uploader
	mount_uploader :image, ImageUploader
	validates_attachment_content_type :clip, :content_type => %w(image/jpeg image/jpg image/png)

	# tagging
	acts_as_taggable
	acts_as_taggable_on :tag_list

	# pagination
	paginates_per 10
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:edit, :new, :update, :destroy, :create]
  after_action  :add_visit_count, only: :show

  # GET /topics
  # GET /topics.json
  def index
    @category = Category.friendly.find(params[:category_id])
    @board = @category.boards.friendly.find(params[:board_id])
    all_topics = @board.topics.order('updated_at DESC').limit(80)
    @topics = Kaminari.paginate_array(all_topics).page(params[:page]).per(10)
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @category = Category.friendly.find(params[:category_id])
    @board = set_board
    @topic = set_topic
		@comment = @topic.comments.build
    @vote = Voting.where(:topic_id => params[:id])
    @voted_num = @vote.size
    @count_of_access = access_num_of_topic
  end

  # GET /topics/new
  def new
    @board = set_board
    @topic = @board.topics.build
  end

  # GET /topics/1/edit
  def edit
    @category = Category.friendly.find(params[:category_id])
    @board = set_board
    @topic = @board.topics.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @category = Category.friendly.find(params[:category_id])
    @board = set_board
    @topic = @board.topics.new(topic_params)
    @topic.category_id = @category.id
    #@topic.user_id = current_user.id

    respond_to do |format|
      if @topic.save
        format.html { redirect_to [@category, @board, @topic], notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
#    @category = Category.friendly.find(params[:category_id])
#    @board = set_board
#    @topic = @board.topics.find(params[:id])
#    @Topic.user_id = current_user.id
#    @topic.category_id = @category.id
#    @topic.board_id = @board.id

    respond_to do |format|
      if @topic.update_attributes(topic_params)
        format.html { redirect_to [@category, @board, @topic], notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = topic_params
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to board_topics_url }
      format.json { head :no_content }
    end
  end

  def add_visit_count
    @visit = ahoy.visit_id
    @topic = set_topic
    TopicVisit.where(topic_id: @topic, visit_id: @visit).first_or_create
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @category = Category.friendly.find(params[:category_id])
      @board    = @category.boards.friendly.find(params[:board_id])
      @topic = @board.topics.find(params[:id])
    end

    def set_board
      @category = Category.friendly.find(params[:category_id])
      @board = @category.boards.friendly.find(params[:board_id])
    end

    def access_num_of_topic
      @topic = set_topic
      TopicVisit.where(topic_id: @topic.id).size
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :name, :content, :board_id, :category_id, :user_id, :image, :tag_list, :visit_id, :clip)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [@category, @board, @topic], :html => {:multipart => true} do |f| %>
<% if @topic.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

  <ul>
    <% @topic.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :title, class: "Gotham" %><br>
  <%= f.text_field :title, class: "full-width formDesign" %>
</div>
<div class="field">
  <%= f.label :content, class: "Gotham" %><br>
  <%= f.text_area :content, class: "full-width formDesign topic-content" %>
</div>
<!--
<div class="field">
  <%= f.label :clip, class: "Gotham" %><br>
  <%= f.file_field :clip %>
</div>
<div class="field">
  <%= f.label :tag_list, class: "Gotham" %><br>
  <%= f.text_field :tag_list, class: "full-width formDesign" %>
</div>
-->
<div class="actions">
  <%= f.submit "Create Topic", class: "btn btn-primary btn-block btn-sign-up Gotham" %>
</div>
<% end %>

app/views/topics/edit.html.erb
<div class="container container-top">
<h1>Editing Topic</h1>

<%= render 'form' %>

</div>

app/views/topics/index.html.erb
<div class="container container-top container-main">
  <div class="row">
    <div class="col-md-12 board_title">
      <p class="board_title"><%= @board.board_name %></p>
    </div>

    <div class="col-md-12">
        <%= link_to 'New Topic', new_category_board_topic_path(@category, @board), class: "btn btn-primary btn-create-topic" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% @topics.each do |t| %>
      <div class="topic">
        <div class="bs-callout bs-callout-info topic_title <%= cycle("odd", "even")%>">
          <p>
            <%= link_to t.title, category_board_topic_path(@category, @board, t) %>
            <p class="topic-created-at"><span><%= t.created_at.to_formatted_s(:extra_short) %></span></p>
          </p>
        </div>
      </div>
      <% end %>
    </div>
    <div class="pagenation txtCenter">
      <%= paginate @topics %>    
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container container-top">
	<div class="row">
		<h1 class="Gotham txtCenter">Topic</h1>
		<div class="col-md-12">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/topics/show.html.erb
	<div class="container container-fluid">
		<div class="row">
			<div class="col-md-12 col-topic-title">

				<span class="access-count"><%= @count_of_access %> views</span>

				<h1 class="topic_title"><%= @topic.title %></h1>
			</div>
			<div class="col-md-12 col-topic-desc-bottom-line">
				<div class="col-topic-desc ProximaNova"><p class="topic-desc"><%= markdown @topic.content %></p></div>
			</div>
		</div>
	</div>
	<!--	<p><%= image_tag(@topic.clip.url(:medium)) %></p> -->
	<!--	<p>Tags: <%= raw @topic.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>  -->
	<!--	<p>Voted Number: <%= @voted_num %></p><%= link_to 'Vote', vote_path(params) %> -->

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="discussion-declaration">Comments</h2>	
			</div>
		</div>

		<div class="row"> 
			<div class="col-md-12 comment-list">
				<% @topic.comments.each_with_index do |comment, num| %>
					<p class="Gotham txt18px">[<%= num %>]</p>
					<div class="comment-desc"><p class="ProximaNova txt18px"><%= plain_markdown comment.body.to_s %></p></div>
				<% end %>
			</div>
		</div>

		<% if (@topic.comments.count < 300) %>
		<div class="row">
			<div class="col-md-12">
				<%= render 'comments/form' %>	
			</div>
		</div>
		<% end %>
	</div>

	<style>
	<%= Pygments.css %>
	</style>
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54682fcb54b3b55c" async="async"></script>

	<script>
		ahoy.trackview();
	</script>