config/routes.rb
Nyanda::Application.routes.draw do
  get "search/result"
	devise_for :users, :controllers => {:registrations => "users/registrations"}, skip: [:sessions, :registrations]
	devise_scope :user do
		get '/in', to: 'devise/sessions#new', as: :new_user_session
		post '/in', to: 'devise/sessions#create', as: :user_session
		get '/out', to: 'devise/sessions#destroy', as: :destroy_user_session

		# users/registrations paths
		post '/joinus', to: 'users/registrations#create', as: :user_registration
		get '/joinus', to: 'users/registrations#new', as: :new_user_registration
		get '/me', to: 'users/registrations#edit', as: :edit_user_registration
		patch '/me', to: 'users/registrations#update', as: nil
		put '/me', to: 'users/registrations#update', as: nil
		delete '/me', to: 'users/registrations#destroy', as: nil
	end
#	devise_for :admin_users, ActiveAdmin::Devise.config
#	ActiveAdmin.routes(self)
	resources :search, :only => [:result, :get_result] do
    collection do
      match 'result' => 'search#result', via: [:get, :post], as: :result
    end
	end
	resources :comments, :only => [:create]
	resources :categories, :only => [:create, :destroy], :path => '/c' do
		resources :boards, :only => [:index], :path => '' do
	    resources :topics, :path => '' do
	    	get 'page/:page', :action => :index, :on => :collection
	    end
	  end
	end
	get 'vote', to: 'votings#vote_to_topic'
	get 'tags/:tag', to: 'tags#index', as: :tag
	get "home/index"
	get 'about', to: 'home#about', as: :about
	get 'sextant_mount', to: "sextant/routes#index"
	root :to => "home#index"

	get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
	# Example of regular route:
	#   get 'products/:id' => 'catalog#view'

	# Example of named route that can be invoked with purchase_url(id: product.id)
	#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

	# Example resource route (maps HTTP verbs to controller actions automatically):
	#   resources :products

	# Example resource route with options:
	#   resources :products do
	#     member do
	#       get 'short'
	#       post 'toggle'
	#     end
	#
	#     collection do
	#       get 'sold'
	#     end
	#   end

	# Example resource route with sub-resources:
	#   resources :products do
	#     resources :comments, :sales
	#     resource :seller
	#   end

	# Example resource route with more complex sub-resources:
	#   resources :products do
	#     resources :comments
	#     resources :sales do
	#       get 'recent', on: :collection
	#     end
	#   end

	# Example resource route with concerns:
	#   concern :toggleable do
	#     post 'toggle'
	#   end
	#   resources :posts, concerns: :toggleable
	#   resources :photos, concerns: :toggleable

	# Example resource route within a namespace:
	#   namespace :admin do
	#     # Directs /admin/products/* to Admin::ProductsController
	#     # (app/controllers/admin/products_controller.rb)
	#     resources :products
	#   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@boards = Board.all
  	@popular_topics = Topic.joins(:topic_visits)
  												 .group('topic_visits.topic_id')
                           .where('topics.created_at >= ?', 1.week.ago)
  												 .order("count(topic_visits.topic_id) desc")
  												 .limit(5)
  	@latest_topics 	= Topic.all(limit: 5, order: 'created_at desc')
  end

  def about
    
  end

  before_filter :set_search

	def set_search
		@search=Topic.search(params[:q])
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container container-top container-main wordBreak contentPadding">
  <div class="row">
    <div class="col-md-12">
      <p class="txtBold txt26px aboutFAQtitle">What's Casualyze?</p>
    </div>
    <div class="col-md-12 ProximaNova txt18px">
    	<p>
    		Casualyze is the idle topic sharing platform for geeks.</br>
    		It maybe have a position as "Reddit only for Engineer", 
    		"categorized and chatty HackerNews".

    	</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <p class="txtBold txt26px aboutFAQtitle">Why bootstrapped Casualyze?</p>
    </div>
    <div class="col-md-12 ProximaNova txt18px">
    	<p>
    		There are some starter cues. The most biggest motivation is 
    		my recongnition that there is no just right hub for idle talk about
    		tech topic.</br> If you wanna discuss or ask a question seriously, 
    		a variety of platforms will support you. However, my wish is not like that.
    		I'd like to discuss Ruby with others and play an exciting religious oppositions with PHP lovers. 

    		</br></br>And at last, honestly, I've felt so lonely in solo programming. 
    	</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <p class="txtBold txt26px aboutFAQtitle">What kind of topic should I post?</p>
    </div>
    <div class="col-md-12 ProximaNova txt18px">
    	<p>
    		Anything welcome. Logging in, you can submit your question about app development, 
				latest launched product, frustration against legacy code.
    	</p>
    </div>
  </div>

    <div class="row">
    <div class="col-md-12">
      <p class="txtBold txt26px aboutFAQtitle">Who made?</p>
    </div>
    <div class="col-md-12 ProximaNova txt18px">
      <p>
        This is made by <a href="https://github.com/timakin">timakin</a>.
      </p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron home-jumbotron">
	<div class="container home-jumbotron-container">
		<h1 class="jumbotron-title-home txtCenter txtWhite">Casualyze</h1>
		<p class="jumbotron-title-desc-home txtWhite">Modern Scheme for Hacker's Topic Sharing</br>Anonymous Community for Engineers</p>
		<br>
		<%= search_form_for @search, url: result_search_index_path, html: { method: :post } do |f| %>
		<div class="input-group home-input">
			<%= f.search_field :title_cont, class: "form-control home-input-form whitePlace", placeholder: "Type anything you want.", :autocomplete => :off  %>
			<div class="input-group-btn">
				<%= f.submit "Go", class: "btn btn-default home-input-btn" %>
			</div>
		</div>
		<% end %>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12">
 			<% @boards.each_slice(3) do |boards| %>
			<div class="btn-group btn-group-justified">
				<% boards.each do |t| %>
				<div class="btn-group">
					<%= link_to t.board_name, category_board_topics_path(Category.find(t.category_id).name, t.board_name), class: "btn btn-primary btn-home-category-list txtWhite" %>
				</div>
				<% end %>
			</div>
			<% end %>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-sm-12">
			<h2 class="list-group-title-home">Popular</h2>
			<ul class="list-group">
				<% @popular_topics.each do |t| %>
				<li class="list-group-item list-group-item-home">
					<%= link_to t.title, category_board_topic_path(Category.find(t.category_id).name, Board.find(t.board_id).board_name, t.id), class: 'list-group-item-title-pop' %>
					<span class="badge list-group-item-badge pull-right"><%= TopicVisit.where(topic_id: t.id).size %></span>
				</li>
				<% end %>
			</ul>
		</div>
		<div class="col-md-6 col-sm-12">
			<h2 class="list-group-title-home">Latest</h2>			
			<ul class="list-group">
				<% @latest_topics.each do |t| %>
				<li class="list-group-item list-group-item-home">
					<%= link_to t.title, category_board_topic_path(Category.find(t.category_id).name, Board.find(t.board_id).board_name, t.id), class: 'list-group-item-title-latest' %>
					<!--<span class="pull-right">1 days ago</span>-->
				</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>



<script>
$(function(){
	var $setElm = $('ul li a.list-group-item-title-pop');
	var cutFigure = '30'; // カットする文字数
	var afterTxt = ' …'; // 文字カット後に表示するテキスト

	$setElm.each(function(){
		var textLength = $(this).text().length;
		var textTrim = $(this).text().substr(0,(cutFigure))

		if(cutFigure < textLength) {
			$(this).html(textTrim + afterTxt).css({visibility:'visible'});
		} else if(cutFigure >= textLength) {
			$(this).css({visibility:'visible'});
		}
	});
});
$(function(){
	var $setElm = $('ul li a.list-group-item-title-latest');
	var cutFigure = '30'; // カットする文字数
	var afterTxt = ' …'; // 文字カット後に表示するテキスト

	$setElm.each(function(){
		var textLength = $(this).text().length;
		var textTrim = $(this).text().substr(0,(cutFigure))

		if(cutFigure < textLength) {
			$(this).html(textTrim + afterTxt).css({visibility:'visible'});
		} else if(cutFigure >= textLength) {
			$(this).css({visibility:'visible'});
		}
	});
});
</script>