config/routes.rb
Nyanda::Application.routes.draw do
  get "search/result"
	devise_for :users, :controllers => {:registrations => "users/registrations"}, skip: [:sessions, :registrations]
	devise_scope :user do
		get '/in', to: 'devise/sessions#new', as: :new_user_session
		post '/in', to: 'devise/sessions#create', as: :user_session
		get '/out', to: 'devise/sessions#destroy', as: :destroy_user_session

		# users/registrations paths
		post '/joinus', to: 'users/registrations#create', as: :user_registration
		get '/joinus', to: 'users/registrations#new', as: :new_user_registration
		get '/me', to: 'users/registrations#edit', as: :edit_user_registration
		patch '/me', to: 'users/registrations#update', as: nil
		put '/me', to: 'users/registrations#update', as: nil
		delete '/me', to: 'users/registrations#destroy', as: nil
	end
#	devise_for :admin_users, ActiveAdmin::Devise.config
#	ActiveAdmin.routes(self)
	resources :search, :only => [:result, :get_result] do
    collection do
      match 'result' => 'search#result', via: [:get, :post], as: :result
    end
	end
	resources :comments, :only => [:create]
	resources :categories, :only => [:create, :destroy], :path => '/c' do
		resources :boards, :only => [:index], :path => '' do
	    resources :topics, :path => '' do
	    	get 'page/:page', :action => :index, :on => :collection
	    end
	  end
	end
	get 'vote', to: 'votings#vote_to_topic'
	get 'tags/:tag', to: 'tags#index', as: :tag
	get "home/index"
	get 'about', to: 'home#about', as: :about
	get 'sextant_mount', to: "sextant/routes#index"
	root :to => "home#index"

	get  '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
	# Example of regular route:
	#   get 'products/:id' => 'catalog#view'

	# Example of named route that can be invoked with purchase_url(id: product.id)
	#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

	# Example resource route (maps HTTP verbs to controller actions automatically):
	#   resources :products

	# Example resource route with options:
	#   resources :products do
	#     member do
	#       get 'short'
	#       post 'toggle'
	#     end
	#
	#     collection do
	#       get 'sold'
	#     end
	#   end

	# Example resource route with sub-resources:
	#   resources :products do
	#     resources :comments, :sales
	#     resource :seller
	#   end

	# Example resource route with more complex sub-resources:
	#   resources :products do
	#     resources :comments
	#     resources :sales do
	#       get 'recent', on: :collection
	#     end
	#   end

	# Example resource route with concerns:
	#   concern :toggleable do
	#     post 'toggle'
	#   end
	#   resources :posts, concerns: :toggleable
	#   resources :photos, concerns: :toggleable

	# Example resource route within a namespace:
	#   namespace :admin do
	#     # Directs /admin/products/* to Admin::ProductsController
	#     # (app/controllers/admin/products_controller.rb)
	#     resources :products
	#   end
end

app/models/board.rb
class Board < ActiveRecord::Base
	extend FriendlyId
	friendly_id :board_name, use: [:slugged, :finders]

	has_many :topics, :dependent => :destroy
  has_many :comments, :through => :topics, :dependent => :destroy
  validates :board_name, :category_id, presence: true

  def should_generate_new_friendly_id?
  	new_record? || slug.blank?
	end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
#    @category = Category.find(params[:category_id])
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @category = Category.friendly.find(params[:category_id])
    @boards = @category.boards.friendly.find(params[:id])
  end

  # GET /boards/new
  def new
    @category = Category.friendly.find(params[:category_id])
    @board = @category.boards.friendly.new
  end

  # POST /boards
  # POST /boards.json
  def create
    @category = Category.friendly.find(params[:category_id])
    @board = @category.boards.friendly.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to [@category, @board], notice: 'Board was successfully created.' }
        format.json { render action: 'show', status: :created, location: @board }
      else
        format.html { render action: 'new' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    @category = Category.friendly.find(params[:category_id])
    respond_to do |format|
      if @category.boards.friendly.update(board_params)
        format.html { redirect_to [@category, @board], notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @category = Category.friendly.find(params[:category_id])
    @board = @category.boards.friendly.find(params[:id])
    @board.destroy
    respond_to do |format|
      format.html { redirect_to category_boards_url(@category) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @category = Category.find(params[:category_id])
      @board = @category.boards.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:board_name)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :board_name %><br>
    <%= f.text_field :board_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">test</div>
    <div class="col-md-4">test</div>
    <div class="col-md-4">test</div>
  </div>    
  <div class="row">
    <% @boards.each do |b| %>
      <div class="col-md-8"><%= b.board_name %></div>
    <% end %>
  </div>
  <table>
    <thead>
      <tr>
        <th>Board name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>  

    <tbody>
      <% @boards.each do |board| %>
        <tr>
  				<td><%= board.board_name %></td>
  			</tr>
      <% end %>
    </tbody>
  </table>  
  <br>  

</div>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Board name:</strong>
  <%= @board.board_name %>
</p>

<%= link_to 'Back', category_boards_path(@category) %>